# Generated by Django 3.2.5 on 2021-07-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('code', models.CharField(max_length=5)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
            options={
                'db_table': 'entries',
            },
        ),
    ]
